#ifndef VENUS_VERSION_HPP
#define VENUS_VERSION_HPP

/**
 * DO NOT EDIT THIS FILE 
 * This file is configurated by cmake to adjust Venus version within the codebase 
 * DO NOT EDIT THIS FILE
 */

#define VENUS_MAJOUR 1  // NOLINT
#define VENUS_MINOUR 0  // NOLINT
#define VENUS_PATCH 0   // NOLINT

#endif  // VENUS_VERSION_HPP
